name: Publish Eslint Config

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    # Checkout repository
    - uses: actions/checkout@v1
      name: Checkout repository

    # Publish to npm registry
    - uses: actions/setup-node@v1
      name: Publish to NPM Registry
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # Publish to github package registry
    - uses: actions/setup-node@v1
      name: Publish to Github Package Repository
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
